# -*- coding: utf-8 -*-
"""python_basic_kadai_008

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VMUfzmIwr11ja7JMCiLoN1GKxtvdz3c4
"""

import random

var = random.randint(0,100)

print(var)

if var % 3 == 0 and var % 5 == 0:
    print("FizzBuzz")
elif var % 5 == 0:
    print("Buzz")
elif var % 3 == 0:
    print("Fizz")
else:
    print(var)