# -*- coding: utf-8 -*-
"""python_basic_14

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AHOeh1RnSk_hmYI7_1hmX0LGrWN7HSHi
"""


#以下のコードを実行するとスコープに関するエラーが発生します。エラーを修正して、正しく計算結果が出力されるようにしてください。

def total():
    price1 = 100
    price2 = 200

    return price1 + price2

tax = 1.1

print (total() * tax)