# -*- coding: utf-8 -*-
"""Python_Basic_Kadai

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YnblpNug-_vmMmXoSZ-pn52Lsi36i-2o
"""

class Human:
    def __init__(self,name,age):
        self.name = name
        self.age = age

    def check_adult(self):
        if self.age > 20:
            return self.name + "は大人です"
        else:
            return self.name + "未成年です"

human1 = Human("侍太郎", 56)
human2 = Human("侍花子", 48)
human3 = Human("侍一郎", 18)
human4 = Human("侍二郎", 10)

humans = [human1,human2,human3,human4]

for human in humans:
    print(human.check_adult())