# -*- coding: utf-8 -*-
"""Python_basic_11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1flJL494r0BHTRbf5OXavBmBApuG8C-Ft
"""

#For文

list = ["水","金","地","火","木","土","天","海","冥"]

for planets in list:
  print(planets)

list = ["水","金","地","火","木","土","天","海","冥"]

i = 0

＃While分

while i < 9:
  print(list[i])

  i = i + 1

my_list = ["水", "金", "地", "火", "木", "土", "天", "海", "冥"]
